"""Render outputs/<frozen>/RESULTS.md from the evaluation CSVs (every number comes from a file)."""

from __future__ import annotations

import argparse
import json

import pandas as pd
import yaml

from nadhir.config import load_config, profile, repo_path


def fmt(v, nd=0):
    if v is None or (isinstance(v, float) and pd.isna(v)):
        return "—"
    return f"{v:.{nd}f}" if isinstance(v, float) else str(v)


def md_table(df: pd.DataFrame) -> str:
    cols = list(df.columns)
    out = ["| " + " | ".join(cols) + " |", "|" + "---|" * len(cols)]
    for _, r in df.iterrows():
        out.append("| " + " | ".join(fmt(r[c], 3) if isinstance(r[c], float) and c.startswith(("alert_day_rate", "f_thr", "observed_frac")) else fmt(r[c]) for c in cols) + " |")
    return "\n".join(out)


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--profile", default="olci_v1")
    a = ap.parse_args(argv)
    cfg = profile(load_config(), a.profile)
    prof = cfg["profile"]
    a.frozen = prof["frozen_name"]
    fz = yaml.safe_load(open(repo_path(f"config/{a.frozen}.yaml")))
    od = repo_path(cfg["outputs"]["out_dir"]) / a.frozen
    prov = json.load(open(od / "provenance.json"))
    leads = pd.read_csv(od / "event_lead_times.csv")
    far = pd.read_csv(od / "false_alarms.csv")
    cov = pd.read_csv(od / "coverage.csv")
    events = [e for e in yaml.safe_load(open(repo_path("events/events.yaml")))["events"]
              if e.get("dataset") == prof["name"]]
    per = cfg["periods"]
    r0 = fz["primary_radius_km"]

    L = []
    L.append(f"# Nadhir hindcast results — `{a.frozen}`\n")
    L.append("_Generated by `python -m nadhir.report`; every number below is read from the CSVs in this folder._\n")
    L.append("## Provenance\n")
    L.append(f"- Detector frozen at tag `{prof['tag']}` → commit `{prov['tag_commit']}`; "
             f"evaluation code commit `{prov['code_commit']}`.")
    L.append(f"- Calibration period (thresholds + climatology): {fz['calibration_period'][0]} → {fz['calibration_period'][1]}.")
    L.append(f"- config/nadhir.yaml sha256 `{prov['config_sha256'][:16]}…`; frozen config sha256 `{prov['frozen_config_sha256'][:16]}…`; events.yaml sha256 `{prov['events_sha256'][:16]}…`.")
    L.append("- Input bin tables (content sha256 of decompressed CSV): " + ", ".join(
        f"`{k}` `{v['content_sha256'][:12]}…`" for k, v in prov["bins_sha256"].items()))
    L.append(f"- Source files (SHA-256 per file): " + ", ".join(f"`data/derived/{m}`" for m in prov["objects_manifests"]) + ".")
    L.append(f"- Data: {prof['data_label']}.\n")

    L.append(f"## 1. Event lead times (primary watch radius {r0} km)\n")
    L.append("`lead_alert_days` = t_ref − first ALERT day. t_ref is the **public report date** (an upper bound on the true "
             "impact onset), so the operational lead time could be shorter by up to `t_ref − t_ref_earliest`: "
             "`lead_alert_min_days` is the lead time if impact began at `t_ref_earliest`. `lead_max_days` = t_ref − last QUIET "
             "observation before the anomaly: the bloom entered the zone somewhere in that interval (satellite gaps).\n")
    p = leads[leads["radius_km"] == r0]
    cols = [c for c in ["event", "evaluation", "outcome", "t_ref", "first_exceed", "first_alert", "lead_alert_days",
                        "lead_alert_min_days", "lead_first_exceed_days", "lead_max_days", "obs_days_in_lookback",
                        "days_in_lookback", "date_precision", "evidence_status"] if c in p.columns]
    L.append(md_table(p[cols]))
    L.append("")
    L.append("Charts: " + ", ".join(f"`event_{e}_r{r0}.png`" for e in p["event"]) + "\n")

    L.append("## 2. Sensitivity to watch radius (frozen at the same time; not tuned on events)\n")
    s = leads.reindex(columns=["event", "radius_km", "outcome", "obs_days_in_lookback", "lead_alert_days", "lead_alert_min_days", "lead_max_days", "f_threshold"])
    L.append(md_table(s.sort_values(["event", "radius_km"])))
    L.append("")

    L.append("## 3. False alarms in periods with no documented disruption\n")
    L.append(f"`heldout_quiet` = {per['heldout_quiet'][0]}..{per['heldout_quiet'][1]} plus years {per['extra_quiet_years']} "
             f"outside event exclusion windows (intake-years excluded: {per.get('quiet_exclude') or 'none'}). "
             "**Out-of-sample.** Undocumented real blooms may exist in these "
             "periods, so these are upper bounds on true false-alarm rates. `calibration (in-sample)` is shown for reference only.\n")
    L.append(md_table(far.sort_values(["set", "intake", "radius_km"])))
    L.append("")

    L.append("## 4. Observation coverage and gaps (NO-DATA days are never filled)\n")
    L.append(md_table(cov[cov["radius_km"] == r0].drop(columns=["radius_km"])))
    L.append("")

    L.append("## 5. Alert activity over documented bloom periods\n")
    L.append("For events with a documented period but no usable single date (season/year precision) and for the "
             "Al Raha limitation test: detector state over the whole period. No lead time is claimed for these.\n")
    lim = pd.read_csv(od / "period_activity.csv")
    L.append(md_table(lim.drop(columns=["evidence_status"])) if len(lim) else "_none_")
    L.append("")
    L.append("## 6. Events not evaluated\n")
    for e in events:
        if e.get("evaluation") == "NOT-EVALUATED":
            L.append(f"- **{e['id']}** — {e['name']} ({e['shutdown_start']}, precision {e['date_precision']}): "
                     "no ocean-colour data reachable for that period in this environment (data/SOURCE_STATUS.md).")
    L.append("")
    open(od / "RESULTS.md", "w").write("\n".join(L))
    print(f"wrote {od / 'RESULTS.md'}")


if __name__ == "__main__":
    main()
